---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: fullconfigsetup-sept16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fullconfigsetup-sept16 
  name: fullconfigsetup-sept16
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi