apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fullconfigsetup-sept16
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fullconfigsetup-sept16 
  name: fullconfigsetup-sept16
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: fullconfigsetup-sept16 
